[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'sha256-m6LLxclyRtUyKJv7W6YqJfXyFhjoqwYL6hEL85BKkYo=' 'sha256-Kjzj2nqI5ZGGOjyXwafSeEwjzCbrusJg1SzlnaSKLFE=' 'sha256-Q7UDa1GrlTa15wiAIFvw+Gfj1hlT1GqTf9eUxrSldYs=' 'sha256-afKegVSrTShzGXueUZ8xjwAJzDqzjw0WTFrL7+P116c=' 'sha256-SFczXEfmyW4bbzWtLtbez+aKOdBzUfA5p6qMHghBWJY=' 'sha256-P4zYLzFAId+v1lFO1IgWXxzl9qBe3xMVwkjBADJkA1w=' 'sha256-ZhpUbTIZTvtd2gJBIJyTDjPbwL7Po8szPZiQP6Ev5Oc=' 'sha256-C87waPXIclOrrpubcglnzBlguKNEv34PbGOF4nJ8K5o=' 'sha256-ZZQGwVCojXwVRz/d2DPUcTY42VwFcO3Mwy2lHg6VxW4=' *.logz.io *.intercomcdn.com www.google-analytics.com www.googletagmanager.com cdn.amplitude.com widget.intercom.io use.fontawesome.com static.hotjar.com script.hotjar.com munchkin.marketo.net; style-src 'self' 'unsafe-inline' *.jquery.com fonts.googleapis.com use.fontawesome.com; connect-src 'self' *.amplitude.com *.intercom.io wss://*.intercom.io *.mktoresp.com http://*.hotjar.com:* https://*.hotjar.com:* http://*.hotjar.io https://*.hotjar.io wss://*.hotjar.com www.google-analytics.com; font-src 'self' use.fontawesome.com fonts.gstatic.com script.hotjar.com data:; frame-src www.googletagmanager.com vars.hotjar.com play.vidyard.com; worker-src 'self' blob:; child-src 'self' blob:; img-src 'self' http://*.hotjar.com https://*.hotjar.com http://*.hotjar.io https://*.hotjar.io logz.io www.google-analytics.com dytvr9ot2sszz.cloudfront.net *.githubusercontent.com data:; media-src 'self' dytvr9ot2sszz.cloudfront.net;"
    
# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  publish = "_site/"
  command = "./build.sh"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  publish = "_site/"
  command = "JEKYLL_ENV=production ./build.sh"


# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview]
  publish = "_site/"
  command = "JEKYLL_ENV=develop ./build.sh"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy]
  publish = "_site/"
  command = "JEKYLL_ENV=develop ./build.sh"

# REDIRECTS. Precede each block with `[[redirects]]`,
# and leave a blank line in between each block.
# Netlify doc on redirects:
# https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

[[redirects]]
  from = "https://logz-docs.netlify.com/*"
  to = "https://docs.logz.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/access-and-authentication/*"
  to = "/user-guide/tokens/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/shippers/*"
  to = "/shipping/log-sources/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/active-directory-winserver.html"
  to = "/shipping/security-sources/active-directory-winserver.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/alcide.html"
  to = "/shipping/security-sources/alcide.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/auditd.html"
  to = "/shipping/security-sources/auditd.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/aws-waf.html"
  to = "/shipping/security-sources/aws-waf.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/azure-activity-logs.html"
  to = "/shipping/security-sources/azure-activity-logs.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/bitdefender.html"
  to = "/shipping/security-sources/bitdefender.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/check-point.html"
  to = "/shipping/security-sources/check-point.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/cisco-asa.html"
  to = "/shipping/security-sources/cisco-asa.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/cisco-meraki.html"
  to = "/shipping/security-sources/cisco-meraki.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/cloudtrail.html"
  to = "/shipping/security-sources/cloudtrail.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/eset.html"
  to = "/shipping/security-sources/eset.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/fail2ban.html"
  to = "/shipping/security-sources/fail2ban.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/falco.html"
  to = "/shipping/security-sources/falco.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/fortigate.html"
  to = "/shipping/security-sources/fortigate.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/gsuite.html"
  to = "/shipping/security-sources/gsuite.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/guardduty.html"
  to = "/shipping/security-sources/guardduty.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/hashicorp-vault.html"
  to = "/shipping/security-sources/hashicorp-vault.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/juniper-srx.html"
  to = "/shipping/security-sources/juniper-srx.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/mcafee-epolicy-orchestrator.html"
  to = "/shipping/security-sources/mcafee-epolicy-orchestrator.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/microsoft-graph.html"
  to = "/shipping/security-sources/microsoft-graph.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/modsecurity.html"
  to = "/shipping/security-sources/modsecurity.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/nginx.html"
  to = "/shipping/security-sources/nginx.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/okta.html"
  to = "/shipping/security-sources/okta.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/openvas.html"
  to = "/shipping/security-sources/openvas.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/ossec.html"
  to = "/shipping/security-sources/ossec.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/palo-alto-networks.html"
  to = "/shipping/security-sources/palo-alto-networks.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sentinelone.html"
  to = "/shipping/security-sources/sentinelone.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sonicwall.html"
  to = "/shipping/security-sources/sonicwall.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sophos.html"
  to = "/shipping/security-sources/sophos.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/stormshield.html"
  to = "/shipping/security-sources/stormshield.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/sysmon.html"
  to = "/shipping/security-sources/sysmon.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/trendmicro.html"
  to = "/shipping/security-sources/trendmicro.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/wazuh.html"
  to = "/shipping/security-sources/wazuh.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/windows-defender.html"
  to = "/shipping/security-sources/windows-defender.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/zeek.html"
  to = "/shipping/security-sources/zeek.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/log-sources/filebeat-for-windows.html"
  to = "/shipping/log-sources/filebeat.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/custom-metrics"
  to = "/shipping/metrics-sources/custom-metrics.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/p8s-sources/*"
  to = "/shipping/prometheus-sources/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/prometheus-sources/aws-redshift-p8s.html"
  to = "/shipping/prometheus-sources/aws-redshift-prometheus.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/p8s-*"
  to = "/user-guide/infrastructure-monitoring/prometheus-:splat"
  status = 301
  force = true  


[[redirects]]
  from = "/user-guide/infrastructure-monitoring/grafana*"   
  to = "/user-guide/infrastructure-monitoring/metrics:splat"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/configure-grafana*"   
  to = "/user-guide/infrastructure-monitoring/configure-metrics:splat"
  status = 301
  force = true

[[redirects]]
  from = "/integrations/alice-slack-chatbot*"   
  to = "https://docs.logz.io"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/prometheus-sources/aws-amazonmq-p8s.html"
  to = "https://docs.logz.io"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/prometheus-sources/aws-classic-elb-p8s.html"
  to = "/shipping/prometheus-sources/aws-classic-elb-prometheus.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/prometheus-sources/aws-lambda-p8s.html"
  to = "/shipping/prometheus-sources/aws-lambda-prometheus.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/prometheus-sources/cloudwatch.html"
  to = "/shipping/prometheus-sources/aws-cloudwatch.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/manage-timeless-accounts.html"
  to = "/user-guide/accounts/manage-the-main-account-and-sub-accounts.html#timeless"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/manage-the-cloud-siem-account.html"
  to = "/user-guide/accounts/manage-the-main-account-and-sub-accounts.html#siem"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/manage-the-infrastructure-monitoring-account.html"
  to = "/user-guide/accounts/manage-the-main-account-and-sub-accounts.html#metrics"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/manage-the-distributed-tracing-account.html"
  to = "/user-guide/accounts/manage-the-main-account-and-sub-accounts.html#tracing"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/log-visualization.html"
  to = "https://docs.logz.io"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/log-shipping/filebeat-troubleshooting/"
  to = "/user-guide/log-troubleshooting/filebeat-troubleshooting.html"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/metrics-sources/custom-metrics.html"
  to = "/shipping/#prometheus-sources"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/metrics-sources/system.html"
  to = "/shipping/#prometheus-sources"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/metrics-sources/consul.html"
  to = "/shipping/#prometheus-sources"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/metrics-sources/envoy.html"
  to = "/shipping/#prometheus-sources"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/elastic-metrics"
  to = "/user-guide/infrastructure-monitoring/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/metrics/integrations.html"
  to = "/user-guide/infrastructure-monitoring/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/metrics/data-sources.html"
  to = "/user-guide/infrastructure-monitoring/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/metrics-explore/"
  to = "/user-guide/infrastructure-monitoring/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/permissions/"
  to = "/user-guide/users/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/distributed-tracing/trace-json"
  to = "/user-guide/distributed-tracing/tracing-tour/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/insights/exceptions/deployments.html"
  to = "/user-guide/logs/exceptions-deployments.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/insights/exceptions/deployments"
  to = "/user-guide/logs/exceptions-deployments.html"
  status = 301
  force = true
  
[[redirects]]
  from = "/user-guide/distributed-tracing/visualize-traces"
  to = "https://docs.logz.io"
  status = 301
  force = true

[[redirects]]
  from = "/shipping/prometheus-sources/prometheus-remote-write-shipping.html"
  to = "/user-guide/infrastructure-monitoring/prometheus-remote-write.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/accounts/flexible-volume-announcement/"
  to = "https://docs.logz.io"
  status = 301
  force = true

[[redirects]]
  from = "/beta-api/"
  to = "/api"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/distributed-tracing/local-jaeger_transition"
  to = "/user-guide/distributed-tracing/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/alerts/view-triggered-alerts.html"
  to = "/user-guide/alerts/event-management.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/kibana/"
  to = "/user-guide/logs/"
  status = 301
  force = true


[[redirects]]
  from = "/user-guide/kibana/best-practices.html"
  to = "/user-guide/logs/best-practices.html"
  status = 301
  force = true


[[redirects]]
  from = "/user-guide/kibana/exceptions-deployments.html"
  to = "/user-guide/logs/exceptions-deployments.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/kibana/log-patterns.html"
  to = "/user-guide/logs/log-patterns.html"
  status = 301
  force = true

[[redirects]]
  from = "/kibana/wildcards/"
  to = "/logs/wildcards/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/kibana/share-import-export/"
  to = "/user-guide/logs/share-import-export/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/infrastructure-monitoring/explore-in-kibana-drilldown-links.html"
  to = "/user-guide/infrastructure-monitoring/explore-in-logs-drilldown-links.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/kibana/mapping/"
  to = "/user-guide/logs/mapping/"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/kibana/mapping/field-not-indexed/"
  to = "/user-guide/logs/mapping/field-not-indexed/"
  status = 301
  force = true
  
 [[redirects]]
  from = "/user-guide/insights/exceptions.html"
  to = "/user-guide/insights/ai-insights.html"
  status = 301
  force = true

[[redirects]]
  from = "/user-guide/log-shipping/telemetry-collector-"
  to = "/user-guide/log-shipping/telemetry-collector"
  status = 301
  force = true
  
[[redirects]]
  from = "/.well-known/acme-challenge/FlcH2tUU5C9QeBVkc5yhe9pmpIA5xYSXw46cbRmYyxc"
  to = "http://dcv.akamai.com/.well-known/acme-challenge/FlcH2tUU5C9QeBVkc5yhe9pmpIA5xYSXw46cbRmYyxc"
  status = 301
  force = true


[[redirects]]
  from = "/user-guide/k360/overview.html#prerequisites"
  to = "/user-guide/k360/kubernetes-360-pre.html"
  status = 301
  force = true


[[redirects]]
  from = "/alerting-and-monitoring/alerts/alert-quotas"
  to = "/user-guide/alerts/"
  status = 301
  force = true

[[redirects]]
  from = "/alerting/alerts.html"
  to = "/user-guide/alerts/"
  status = 301
  force = true